### ISSUE TITLE
환경 구축 작업

### ISSUE THREAD

**Issue by hyeon-gyu** [team-moeum/checkmate-backend#3]
## TODO
- [x] 멀티프로필 환경 세팅 : gitignore 편집 
- [x] 로컬 테스트를 위한 H2 DB 라이브러리 추가
- [x] 도커파일 작성
- [x] 워크플로우 파일 작성
- [x] swagger

**Comment by seungdeok** [comment]
@hyeon-gyu 
#2 이슈는 본 이슈에서 진행부탁드립니다:)
